name: Test

on: 
  push:
    branches:
      - "test-e2e"  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Install Cardano tools
      uses: Qafana/cardano-tools-action@v1

    - name: Test
      run: make test-e2e
