name: Test

on: 
  push:
    branches:
      - "test-e2e"  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Install Cardano node
      uses: milos-ethernal/cardano-node-action@bf79cdb680c317f5cd8c60b0905f2e72639bb371

    - name: Node version
      run: cardano-node --version

    - name: CLI version
      run: cardano-cli --version

    
